<a href="https://colab.research.google.com/github/yogeshwenwu/GAN/blob/main/Task_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Task_01: Predict Restaurant Ratings

###Objective:
> *Build a machine learning model to predict the aggregate rating of a restaurant based on other features.*

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("Dataset.csv")
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

###Step_01 : Preprocessing the Dataset

####==>  *Handling missing values*

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

``` 9  | Cuisines | 9542 | non-null |   object```

Column Cuisines has **9** missing values

In [ ]:
df['Cuisines'].fillna(value='unknown',inplace=True)
df['Cuisines'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 9551 entries, 0 to 9550
Series name: Cuisines
Non-Null Count  Dtype
--------------  -----
9551 non-null   object
dtypes: object(1)
memory usage: 74.7+ KB

>
####==> Dimensionality Reduction

In [ ]:
x = df.drop(['Restaurant ID','Restaurant Name','Country Code','City', 'Address', 'Locality', 'Locality Verbose', 'Rating color', 'Aggregate rating'], axis=1)
y = df['Aggregate rating']
x

,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Rating text,Votes
0,121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),Yes,No,No,No,3,Excellent,314
1,121.014101,14.553708,Japanese,1200,Botswana Pula(P),Yes,No,No,No,3,Excellent,591
2,121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),Yes,No,No,No,4,Very Good,270
3,121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),No,No,No,No,4,Excellent,365
4,121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),Yes,No,No,No,4,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...
9546,28.977392,41.022793,Turkish,80,Turkish Lira(TL),No,No,No,No,3,Very Good,788
9547,29.041297,41.009847,"World Cuisine, Patisserie, Cafe",105,Turkish Lira(TL),No,No,No,No,3,Very Good,1034
9548,29.034640,41.055817,"Italian, World Cuisine",170,Turkish Lira(TL),No,No,No,No,4,Good,661
9549,29.036019,41.057979,Restaurant Cafe,120,Turkish Lira(TL),No,No,No,No,4,Very Good,901
9550,29.026016,40.984776,Cafe,55,Turkish Lira(TL),No,No,No,No,2,Very Good,591

>
####==>  Encoding Categorical Variables

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for column in x:
    x[column] = encoder.fit_transform(x[column])

In [ ]:
x.head()

,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Rating text,Votes
0,8042,384,920,73,0,1,0,0,0,2,1,314
1,8041,382,1111,75,0,1,0,0,0,2,1,545
2,8053,388,1671,113,0,1,0,0,0,3,5,270
3,8050,391,1126,81,0,0,0,0,0,3,1,362
4,8055,390,1122,81,0,1,0,0,0,3,1,229

>
####==>  Splitting the data into training and testing sets

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
print("x_train :\n",x_train)
print()
print("y_train :\n",y_train)

x_train :
       Longitude  Latitude  Cuisines  Average Cost for two  Currency  \
2629       3218      2883      1554                    55         4
4685       2867      6645       549                    55         4
6159       5958      5311      1618                    61         4
9197        783       581       589                    66         4
5605       4736      7968      1306                    32         4
...         ...       ...       ...                   ...       ...
5734        572       203      1329                    32         4
5191       4307      2585      1514                    62         4
5390       3938      2468      1699                    36         4
860        7728      8137      1498                    84         4
7270       3321      7909      1514                    61         4

      Has Table booking  Has Online delivery  Is delivering now  \
2629                  0                    0                  0
4685                  0                    0                  0
6159                  0                    0                  0
9197                  0                    0                  0
5605                  0                    0                  0
...                 ...                  ...                ...
5734                  0                    0                  0
5191                  0                    1                  0
5390                  0                    0                  0
860                   0                    0                  0
7270                  0                    1                  0

      Switch to order menu  Price range  Rating text  Votes
2629                     0            1            2     44
4685                     0            1            0     10
6159                     0            1            3      0
9197                     0            2            2    226
5605                     0            0            3      0
...                    ...          ...          ...    ...
5734                     0            0            3      0
5191                     0            1            2     75
5390                     0            0            3      0
860                      0            3            5     66
7270                     0            1            2    195

[6685 rows x 12 columns]

y_train :
 2629    3.9
4685    3.1
6159    0.0
9197    3.9
5605    0.0
       ...
5734    0.0
5191    3.8
5390    0.0
860     4.4
7270    3.7
Name: Aggregate rating, Length: 6685, dtype: float64

###Step_02 : Select a Regression Algorithm

*(e.g., linear regression,decision tree regression) and train it on the training data.*

In [ ]:
from sklearn.ensemble import RandomForestRegressor

reg = RandomForestRegressor()

In [ ]:
reg.fit(x_train, y_train)

RandomForestRegressor()

###Step_03 : Evaluate the model's performance using appropriateregression metrics

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
y_hat = reg.predict(x_test)

####==> *Mean Squared Error on the testing data.*

In [ ]:
mse = mean_squared_error(y_test, y_hat)

print(f'Mean Squared Error :  {mse}')

Mean Squared Error :  0.029074806427076046

####==> *R-squared on the testing data.*

In [ ]:
r2_scr = r2_score(y_test, y_hat)

print(f'R-Squared:  {r2_scr}')

R-Squared:  0.9871508691299862

###Step_04 : Interpret the model's results and analyze the mostinfluential features affecting restaurant ratings.

In [ ]:
ftr_imp = reg.feature_importances_

column = x_train.columns

imp_ftr = pd.DataFrame({'Feature': column, 'Importance':ftr_imp})

imp_ftr_srt = imp_ftr.sort_values(by='Importance', ascending = False)
print(imp_ftr_srt)

                 Feature  Importance
11                 Votes    0.900547
10           Rating text    0.088848
0              Longitude    0.002934
1               Latitude    0.002884
2               Cuisines    0.002386
3   Average Cost for two    0.001647
6    Has Online delivery    0.000345
9            Price range    0.000225
5      Has Table booking    0.000114
4               Currency    0.000041
7      Is delivering now    0.000029
8   Switch to order menu    0.000000

In [ ]:
print('Features')

print(imp_ftr_srt.head().Feature.to_string(index = False))

Features
      Votes
Rating text
  Longitude
   Latitude
   Cuisines